# production:
#   storage_account_name: ENV['AZURE_STORAGE_ACCOUNT']
#   storage_access_key:   ENV['AZURE_STORAGE_ACCESS_KEY']
#   container:            ENV['AZURE_CONTAINER_NAME']


development:
  CDN_HOST: "http://localhost:3000/"
  FACEBOKK_APP_ID: "1976550559234614"
  FACEBOKK_APP_SECRET: "538d5fd262c291083b51ae08a7bacad4"