# production:
#   storage_account_name: ENV['AZURE_STORAGE_ACCOUNT']
#   storage_access_key:   ENV['AZURE_STORAGE_ACCESS_KEY']
#   container:            ENV['AZURE_CONTAINER_NAME']


development:
  CDN_HOST: "http://localhost:3000/"